
#+TITLE: Derivatives
#+AUTHOR: Laurent Garnier
#+LATEX_HEADER: \usepackage{amssymb}

* Source

  This content is a part of [[https://laurentgarnier.podia.com/pratiques-mathematiques-en-1ere][Pratiques Mathematiques]] (in French)
  created by Laurent Garnier.

  This document (in English) has borrowed some inspiration from the
  Oxford IB (International Baccalaureate) Diploma programme that you
  can get on Amazon: [[https://amzn.to/3SamRaK]]

  You can get the full course here:
  [[https://laurentgarnier.podia.com/pratiques-mathematiques-en-1ere]]
  
  
* Basic Formulas
** General definition

   The derivative in mathematics is the rate at which one quantity
   alters in relation to another. *Differentiation* is the name given to
   the process of determining the derivative. The calculus is a branch
   of mathematics that is based on these concepts.
   
*** Example

    At any time $t$ seconds, $t > 1$, and $d = -t^2 + t + 6$, a ball
    traveling toward the edge of a ping-pong table is $d$ cm away from
    the edge. Calculate the ball's average speed between the first and
    third seconds.

    Average speed = total distance $\div$ total time.

    \[\dfrac{\left[-(3)^2 + 3 + 6\right]-\left[-(1)^2+1+6\right]}{3-1}
    = -3\]

    The speed of the ball is 3 cm$s^{-1}$.

*** Definition 1

    Typically, a function's average rate between two input values, $x_1$
    and $x_2$, is provided by

    \[\dfrac{\Delta y}{\Delta x} = \dfrac{f(x_2)-f(x_1)}{x_2-x_1}\]

    (read as 'the change in $y$ divided by the change in $x$' where
    $\Delta$ is the Greek letter delta.)

    
*** Definition 2
    
   The gradient of a curve \[y = f(x)\] at the point \[(x_0, f(x_0))\] is
   \[ \lim_{h\to 0}\dfrac{f(x_0 + h) - f(x_0)}{h} \]  provided this
   limit exists.

   If this limit exists the gradient of of a curve \[y = f(x)\] at the
   point \[(x_0, f(x_0))\] is written \[f'(x_0)\]

*** Examples
**** Example 1
     
     Find the gradient of the curve $y = x^2$ at the point $x_0 = -2$.

**** Solution 1


     \begin{align*}
     \dfrac{\Delta y}{\Delta x} &= \dfrac{(-2+h)^2-(-2)^2}{(-2+h)-(-2)}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{4-4h+h^2-4}{h}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{-4h+h^2}{h}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{h(-4+h)}{h}\
     \dfrac{\Delta y}{\Delta x} &= -4+h
     \end{align*}


     Hence \[\lim_{h\to 0} (-4+h) = -4\]

     

**** Example 2

     Find the points on the curve $y = \dfrac{1}{x}$ such that the
     gradient at these points is $-\dfrac{1}{9}$.

**** Solution 2

     Consider the point $\left(x_0, \dfrac{1}{x_0}\right)$ and a
     neighboring point $\left(x_0 + h, \dfrac{1}{x_0 + h}\right)$.



     \begin{align*}
     \dfrac{\Delta y}{\Delta x} &= \dfrac{\dfrac{1}{x_0 + h}-\dfrac{1}{x_0}}{(x_0+h)-x_0}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{\dfrac{x_0-(x_0+h)}{x_0(x_0+h)}}{h}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{\dfrac{-h}{x_0^2+x_0h}}{h}\
     \dfrac{\Delta y}{\Delta x} &= \dfrac{-1}{x_0^2+x_0h}
     \end{align*}


     Therefore:

     \[\lim_{h\to 0} \dfrac{-1}{x_0^2+x_0h} = -\dfrac{1}{x_0^2}\]

     So $-\dfrac{1}{x_0^2} = -\dfrac{1}{9}$ hence $x_0 = \pm 3$.

     The points are $\left(3, \dfrac{1}{3}\right)$ and $\left(-3,
     -\dfrac{1}{3}\right)$.

     

     

*** Exercices

    1. Find the gradient of the curve at the given value of $x$.
       1. $y = 3x^2 - 2x - 1$ at $x = 5$
       2. $y = \dfrac{3}{x}$ at $x = -2$
       3. $y = x^3$ at $x = 7$
    2. Find the point on the curve $y = \dfrac{1}{x^2}$, such that the
       gradient at the point is 3.
    3. Find the gradient function of the curve $y = 2x^2 +
       \dfrac{1}{x}$ and then the point on the curve where the
       gradient is 3.

*** Definition 3

    The *derivative*, or *gradient function*, of a function $f$ with
    respect to $x$ is the function \[f'(x) = \lim_{h\to
    0}\dfrac{f(x+h)-f(x)}{h}\], provided this limit exists.

    If $f'$ exists, then $f$ has a derivative at $x$, or is
    *differentiable* at $x$. ($f'(x)$ is read '$f$ dash' or '$f$
    prime', of $x$.) Another notation for the derivative is
    $\dfrac{dy}{dx}$, the derivative of the function $y = f(x)$ with
    respect $x$.

    A function is differentiable if the derivative exists for all $x$
    in the domain of $f$.

*** Examples
**** Example 1
     
    Find $f'(x)$ given that $f(x) = 2x^2 + x$, and hence find the
    gradient of the function at $x = -3$.

    \begin{align*}
    f'(x) &= \lim_{h\to 0}\dfrac{2(x+h)^2+(x+h)-(2x^2+x)}{h}\
    f'(x) &= \lim_{h\to 0}(4x+1+2h)\
    f'(x) &= 4x+1\
    f'(-3) &= -11
    \end{align*}
    
**** Example 2

     A particle moves in a straight line so that its position from its
     starting point at any time $t$, in seconds, is given by $s =
     4t^2$, where $s$ is in metres. The particle passes through a
     point $P$ when $t = a$ and then sometime later it passes through
     point $Q$ when $t = a + h$. Find the average velocity as the
     particle travels from point $P$ to point $Q$, and deduce its
     velocity at the instant it passes through $P$.

     $P(a, 4a^2)$ and $Q(a+h, 4(a+h)^2)$

     \begin{align*}
     \text{Average velocity } &= \dfrac{4(a+h)^2-4a^2}{(a+h)-a}\
     \text{Average velocity } &= \dfrac{4(a^2+2ah+h^2)-4a^2}{h}\
     \text{Average velocity } &= \dfrac{4h^2+8ah}{h}\
     \text{Average velocity } &= h\dfrac{4h+8a}{h}\
     \text{Average velocity } &= 4h+8
     \end{align*}

     Velocity at P = 8am$s^{-1}$.
     
*** Exercices

    1. Find the gradient function of the given curve, and then the
       value of the gradient to the curve at the given point.
       1. $y = 4x^2 - 5x + 1$ at $x = \dfrac{3}{8}$.
       2. $y = \sqrt{x}$ at $x = 4$.
       3. $y = \dfrac{2}{x}$ at $x = 3$.
       4. $y = \sqrt{x - 2}$ at $x = 11$.
       5. $y = \dfrac{1}{\sqrt{x}}$ at $x = 25$.
    2. A particle moves in a straight line so that its position from
       its starting point after $t$ seconds is $12-5t^2$. If the
       particles passes through point $A$ when $t = a$, and point $B$
       when $t = a + h$, find
       1. the average velocity of the object as it moves from $A$ to
          $B$
       2. the velocity as it passes through point $A$.

